-- Seed: Ohad's owned books (Own?=yes) → shared catalog + his listings.
-- Run AFTER signing into the APP once (so the auth user + profile exist).
do $$
declare me uuid;
declare bid uuid;
begin
  select id into me from auth.users where email = 'ohadzs100@gmail.com';
  if me is null then raise exception 'Sign into the app once first, then re-run.'; end if;
  insert into profiles (id, name) values (me, 'אוהד') on conflict (id) do nothing;
  insert into books (title, author, created_by) values ('סודותיו של מורה נבוכים', 'מיכה גודמן', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('כתבי אפלטון - כרך ראשון', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('יוהנס קפלר : האיש ופעלו', 'ארתור קסטלר', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('אסתטיקה אנליטית', 'עדי צמח', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('מכתבים לאחותי', 'יוסף אגסי', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('בעיות הפילוסופיה', 'ברטרנד ראסל', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('המיתולוגיה של הרוע', 'שוהם', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('מגמות בתולדות הספקנות', 'עדי פרוש', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('מבחר מסות', 'מישל דה מונטיין', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('יסוריי ורתר הצעיר', 'גתה', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('מאמר על המתודה', 'דקארט', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('זמן ותודעה', 'אבשלום אליצור', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('המשפט האחרון של פרמה', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('הגיונות', 'רנה דקארט', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('21 מחשבות על המאה ה-21', 'יובל נוח הררי', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('הפיסיקה של המאה ה-20', 'יובל נאמן', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('עולמה הקסום של השינה', 'פרץ לביא', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('טירוף, סטייה ויצירה', 'שלמה גיורא שוהם', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('אהבת נפש', 'יהושע בר-יוסף', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('כה אמר זרתוסטרא', 'פרידריך ניטשה', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('ראשית הבודהיזם', 'שלמה בידרמן', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('הדרשה על נפילת רומי', 'זרום פרארי', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('הבשורה על פי ישו', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('רודף העפיפונים', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('ההיסטוריה של המחר', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('חשיבה חדה', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('קיצור תולדות האנושות', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('חשוב והתעשר', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('לא רציונלי אבל לא נורא', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('שיחות על תורת המשחקים', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('סודו של איש עשיר', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('Atomic habits', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('אינטליגנציה רגשית', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('The five people you meet in heaven', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('כה אמר וורן באפט', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('ארבע ההסכמות', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('מצוינים', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('לא רציונלי ולא במקרה', 'דן אריאלי', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('הפסיכולוגיה של ההצלחה', 'מאיר לירז', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('אומנות ההקשבה לפעימות הלב', 'יאן פיליפ סנדקר', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('אומנות המלחמה', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('מטרות החינוך', 'וייטהד', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('ברטרנד ראסל היקר', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('קולנוע ופילוסופיה', 'הנרי אונגר', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('הצחוק', 'ברגסון', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('המחשבה הפיסיקאלית בהתהוותה', 'שמואל סמבורסקי', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('החברה הפתוחה ואויביה', 'פופר', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('The History of Western Philosophy', 'Bertrand Russell', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('זרמים ראשיים במיסטיקה היהודית', 'גרשום שלום', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('כתבי אפלטון - כרך שני', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('מלחמה ושלום', 'טולסטוי', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('איליאדה', 'הומרוס', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('מסכת טבע האדם', 'דוד יום', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('בראשית', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
end $$;
