-- Seed: Ohad's 83 Hebrew read books into the shared catalog + his listings.
-- Run AFTER you have signed in once (so your auth user + profile exist).
-- Matches your account by email; change it if you signed up differently.
do $$
declare me uuid;
declare bid uuid;
begin
  select id into me from auth.users where email = 'ohadzs100@gmail.com';
  if me is null then raise exception 'Sign in once first, then re-run.'; end if;
  insert into profiles (id, name) values (me, 'אוהד') on conflict (id) do nothing;
  insert into books (title, author, created_by) values ('סודותיו של מורה נבוכים', 'מיכה גודמן', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('כתבי אפלטון - כרך ראשון', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('יוהנס קפלר : האיש ופעלו', 'ארתור קסטלר', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('פילוסופיה של הטכנולוגיה', 'יוסף אגסי', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('אסתטיקה אנליטית', 'עדי צמח', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('פילוסופיה של החינוך', 'יוסף אגסי ודב רפל', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('מכתבים לאחותי', 'יוסף אגסי', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('בעיות הפילוסופיה', 'ברטרנד ראסל', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('אקזיסטנציאליזם הוא הומוניזם', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('דון ג׳ואן (הצגה)', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('הזר', 'קאמי', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('אדיפוס המלך', 'סופוקלס', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('המיתולוגיה של הרוע', 'שוהם', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('אות קיין', 'שלמה גיורא שוהם', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('פואטיקה', 'אריסטו', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('תולדות הפילוסופיה החדשה', 'יוסף אגסי', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('הנאורות החדשה', 'יוסף אגסי', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('הריפוי של שופנהאואר', 'ארווין', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('זיכרון ילדות יפה במיוחד', 'חיים שפירא', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('מחשבות לעת לילה', 'חיים שפירא', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('כתבים מן המרתף', 'דוסטויובסקי', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('מגמות בתולדות הספקנות', 'עדי פרוש', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('מבחר מסות', 'מישל דה מונטיין', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('יסוריי ורתר הצעיר', 'גתה', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('מאמר על המתודה', 'דקארט', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('זמן ותודעה', 'אבשלום אליצור', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('על העיוורון', 'ז׳וזה סארמאמגו', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('ערבה עיוורת, עלמה נמה', 'מורקמי', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('המשפט האחרון של פרמה', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('הגיונות', 'רנה דקארט', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('תליין אהבה', 'ארווין יאלום', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('21 מחשבות על המאה ה-21', 'יובל נוח הררי', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('קורות הציפור המכנית', 'הרוקי מורקמי', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('הפיסיקה של המאה ה-20', 'יובל נאמן', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('עולמה הקסום של השינה', 'פרץ לביא', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('טירוף, סטייה ויצירה', 'שלמה גיורא שוהם', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('תולדות הפילוסופיה - מהרנסאנס ועד קאנט', 'בן עמי שרפשטיין', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('אהבת נפש', 'יהושע בר-יוסף', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('כה אמר זרתוסטרא', 'פרידריך ניטשה', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('גסטבי הגדול', 'פ׳ סקוט פיצג׳רלד', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('ראשית הבודהיזם', 'שלמה בידרמן', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('הדרשה על נפילת רומי', 'זרום פרארי', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('אזורי המשגה שלך', 'ויין דייר', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('הפילוסופים הגדולים - אפלטון', 'ברנארד ויליאמס', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('קיצור תולדות הזמן', 'סטיבן הוקינג', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('יער נורווגי', 'הרוקי מורקמי', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('כשניטשה בכה', 'ארווין יאלום', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('הבשורה על פי ישו', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('רודף העפיפונים', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('לחשוב מהר לחשוב לאט', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('המטרה', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('קפקא על החוף', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('האלכימאי', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('ההיסטוריה של המחר', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('חשיבה חדה', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('קיצור תולדות האנושות', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('ילד 44', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('כולנו בני חלוף', 'ארווין יאלום', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('חשוב והתעשר', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('לא רציונלי אבל לא נורא', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('שיחות על תורת המשחקים', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('סודו של איש עשיר', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('אינטליגנציה רגשית', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('אתה, המושך בחוטים', 'ויין דייר', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('כה אמר וורן באפט', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('ארבע ההסכמות', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('מצוינים', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('לא רציונלי ולא במקרה', 'דן אריאלי', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('תורת המשחקים', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('הפסיכולוגיה של ההצלחה', 'מאיר לירז', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('אומנות ההקשבה לפעימות הלב', 'יאן פיליפ סנדקר', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('שפת המכירות - שיטת אימפקט למכירות', 'דניאל דודזון', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('אומנות המלחמה', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('מטרות החינוך', 'וייטהד', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('כיבוש האושר', 'ברטרנד ראסל', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('ברטרנד ראסל היקר', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('עולם בדים', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('בימאים ואנשי קולנוע על הקולנוע', null, me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('ילדי הצל', 'בן ציון תומר', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('פרחים לעכבר לבן', 'דניאל קיז', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('קולנוע ופילוסופיה', 'הנרי אונגר', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('אהבה זה לא סכין', 'זאב ברגמן', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
  insert into books (title, author, created_by) values ('הצחוק', 'ברגסון', me) returning id into bid;
  insert into listings (book_id, owner) values (bid, me) on conflict do nothing;
end $$;
